import { liveSqlite, manifestOf } from './clone-fixture.js';
import type { CodecManifestInput, TableInput } from '../codecs/manifest.js';

type Columns = TableInput['columns'];
const int = { codec: 'integer', nullable: false } as const;
const nullableInt = { codec: 'integer', nullable: true } as const;
const text = { codec: 'text', nullable: false } as const;
const table = (columns: Columns, primaryKey: string[] = ['id']): CodecManifestInput['tables'][string] => ({ columns, primaryKey });

// ---------------------------------------------------------------------------------------------------------------
// A fixture whose two sides deliberately differ: epoch-ms vs timestamptz, 0/1 vs boolean, ISO text preserved,
// int8 beyond 2^53, jsonb vs JSON text, a generated column, descending and AUTOINCREMENT sequences, FK cycle and
// self reference, composite text PK with non-ASCII, uuid PK stored in mixed case.
export const BIG_MANIFEST = manifestOf({
  version: 1,
  tables: {
    a: table({ id: int, b_id: nullableInt }),
    b: table({ id: int, a_id: nullableInt }),
    node: table({ id: int, parent_id: nullableInt }),
    events: table({
      id: int,
      label: text,
      at_ms: { codec: 'timestamp-epoch-ms', preserveInteger: false, nullable: false },
      iso: { codec: 'timestamp-iso', nullable: false },
      flag: { codec: 'boolean', nullable: false },
      big: { codec: 'bigint', nullable: false },
      dbig: { codec: 'bigint', nullable: true, generated: true },
      doc: { codec: 'json-text', preserveText: false, nullable: true },
      raw: { codec: 'blob', nullable: true },
      note: { codec: 'text', nullable: true },
      ratio: { codec: 'real', nullable: false },
    }),
    ticket: table({ id: int }),
    people: table({ country: text, name: text, age: nullableInt }, ['country', 'name']),
    tokens: table({ id: { codec: 'uuid-text', nullable: false }, label: text }),
    labels: table({ name: text }, ['name']),
  },
});
export const BIG_DDL = [
  'create table a(id bigint primary key, b_id bigint)',
  'create table b(id bigint primary key, a_id bigint)',
  'alter table a add constraint a_b_fk foreign key (b_id) references b(id) on delete cascade',
  'alter table b add constraint b_a_fk foreign key (a_id) references a(id) deferrable initially deferred',
  'create table node(id bigint primary key, parent_id bigint references node(id))',
  `create table events(id bigint generated by default as identity primary key, label text not null, at_ms timestamptz not null, iso text not null, flag boolean not null,
     big bigint not null, dbig bigint generated always as (big * 2) stored, doc jsonb, raw bytea, note text, ratio double precision not null)`,
  'create table ticket(id bigint generated by default as identity (start with -1 increment by -1 minvalue -1000 maxvalue -1) primary key)',
  'create table people(country text not null, name text not null, age bigint, primary key (country, name))',
  'create table tokens(id uuid primary key, label text not null)',
  'create table labels(name text primary key)',
];
export const NASTY = 'tab\there\nnewline\r\\N literal \\. dot \\\\ double ünï 😀';
/** The SQLite schema of the big fixture, with no rows: what an app's own SQLite migrations would produce. */
export const BIG_SCHEMA: readonly string[] = [
    'create table a(id integer primary key, b_id integer)',
    'create table b(id integer primary key, a_id integer)',
    'create table node(id integer primary key, parent_id integer references node(id))',
    `create table events(id integer primary key autoincrement, label text not null, at_ms integer not null, iso text not null, flag integer not null,
       big integer not null, dbig integer generated always as (big * 2) stored, doc text, raw blob, note text, ratio real not null)`,
    'create table ticket(id integer primary key)',
    'create table people(country text not null, name text not null, age integer, primary key (country, name))',
    'create table tokens(id text primary key, label text not null)',
    'create table labels(name text collate nocase primary key)',
  ];

/** The big fixture's rows. */
export const BIG_DATA: readonly string[] = [
    "insert into labels values ('apple'), ('Apple2'), ('Banana'), ('cherry')",
    'insert into a values (1, null), (2, null)',
    'insert into b values (10, 1), (11, 2)',
    'update a set b_id = 10 where id = 1',
    'insert into node values (1, null), (2, 1), (3, 2)',
    'insert into ticket values (-1), (-5), (-3)',
    ...[1, 2, 3, 4, 5].map((n) => `insert into events(label, at_ms, iso, flag, big, doc, raw, note, ratio) values ('row ${n}', ${1709280000123 + n}, '2026-01-01T00:00:00Z', ${n % 2}, 9007199254740993, '{"b":1,"a":[1.0]}', x'00ff5c09', ${n === 1 ? 'null' : "''"}, ${n}.5)`),
    `update events set label = '${NASTY.replaceAll("'", "''")}' where id = 2`,
    'delete from events where id > 3',
    "insert into people values ('DE', 'Zoë', 1), ('de', 'zoë', null), ('É', 'x', 2), ('é', 'x', 3), ('Z', 'a', 4), ('z', 'a', 5), ('日本', '山田', 6), ('😀', 'y', 7), ('', 'empty', 8), ('a', 'b\tc', 9)",
    "insert into tokens values ('FFFFFFFF-0000-4000-8000-000000000001', 'upper'), ('aaaaaaaa-0000-4000-8000-000000000002', 'lower'), ('00000000-0000-4000-8000-000000000003', 'zero')",
  ];

export const BIG_LIVE = (dir: string): string => liveSqlite(dir, [...BIG_SCHEMA, ...BIG_DATA]);
