import { startCommitProxy } from '../test-support/commit-proxy.js';
import { rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { liveSqlite, scratchDir, targetDatabase, type TargetDatabase } from '../test-support/clone-fixture.js';
import { startThrowawayPostgres, type ThrowawayPostgres } from '../test-support/embedded-pg.js';
import { runCloneCli, TARGET_URL_ENV } from './cli.js';
import { CloneRefusal } from './errors.js';
import { planClone } from './plan.js';
import { manifestOf } from '../test-support/clone-fixture.js';
import { loadTopology } from './topology.js';

let server: ThrowawayPostgres;
let db: TargetDatabase;
const dir = scratchDir();
const MANIFEST = { version: 1, tables: { items: { primaryKey: ['id'], columns: { id: { codec: 'integer', nullable: false }, name: { codec: 'text', nullable: false } } } } };
const manifestPath = join(dir, 'manifest.json');
let live = '';
let url = '';

beforeAll(async () => {
  server = await startThrowawayPostgres();
  db = await targetDatabase(server, ['create table items(id bigint generated by default as identity primary key, name text not null)']);
  live = liveSqlite(dir, ['create table items(id integer primary key, name text not null)', "insert into items values (4, 'a')"]);
  writeFileSync(manifestPath, JSON.stringify(MANIFEST));
  url = `postgres://${db.config.user}:${db.config.password}@${db.config.host}:${db.config.port}/${db.config.database}`;
}, 180_000);

afterAll(async () => {
  await db?.close();
  await server?.stop();
  rmSync(dir, { recursive: true, force: true });
}, 60_000);

async function run(args: string[], env: NodeJS.ProcessEnv = { [TARGET_URL_ENV]: url }): Promise<{ code: number; out: string; err: string }> {
  let out = '';
  let err = '';
  const code = await runCloneCli(args, env, { out: (t) => void (out += `${t}\n`), err: (t) => void (err += `${t}\n`) });
  return { code, out, err };
}

const base = (): string[] => ['--from-live', live, '--manifest', manifestPath, '--writers-stopped', '--plan-only'];
const confirm = (): string[] => ['--confirm-production', `${db.config.host}:${db.config.port}/${db.config.database}`];

describe('db-kit clone --plan-only', () => {
  it('prints the plan and exits 0 on a clean confirmed target', async () => {
    const { code, out, err } = await run([...base(), ...confirm()]);
    expect({ code, err }).toEqual({ code: 0, err: '' });
    expect(out).toContain('plan OK: no refusals');
    expect(out).toContain('items: 1 rows');
    expect(out).toContain('RESTART WITH 5');
    expect(out).toContain('PRODUCTION');
    expect(out + err).not.toContain(db.config.password ?? 'x');
  });

  it('--json prints a parseable plan with 64-bit values as strings', async () => {
    const { code, out } = await run([...base(), ...confirm(), '--json']);
    expect(code).toBe(0);
    const plan = JSON.parse(out) as { ok: boolean; sequences: { restartWith: string; increment: string }[]; target: { production: boolean } };
    expect(plan.ok).toBe(true);
    expect(plan.sequences).toMatchObject([{ restartWith: '5', increment: '1' }]);
    expect(plan.target.production).toBe(true);
  });

  it('exits 1 and lists refusals (production without --confirm-production)', async () => {
    const { code, out } = await run(base());
    expect(code).toBe(1);
    expect(out).toContain('REFUSED (1):');
    expect(out).toContain('production-unconfirmed');
  });

  it('refuses without --writers-stopped', async () => {
    const { code, err } = await run(base().filter((a) => a !== '--writers-stopped'));
    expect(code).toBe(1);
    expect(err).toContain('writers-not-stopped');
  });

  it('takes the target URL only from the environment', async () => {
    const missing = await run([...base(), ...confirm()], {});
    expect({ code: missing.code, err: missing.err.trim() }).toEqual({ code: 1, err: 'REFUSED: target-url-missing' });
    expect((await run([...base(), '--url', url])).code).toBe(2);
    expect((await run([...base(), ...confirm()], { [TARGET_URL_ENV]: 'ftp://nope' })).err).toContain('target-url-invalid');
    expect((await run([...base(), ...confirm()], { [TARGET_URL_ENV]: 'file:/tmp/x.db' })).err).toContain('target-not-postgres');
  });

  it('exits 2 on a usage error and unless exactly one of --plan-only, --dry-run, --execute is given', async () => {
    expect((await run(['--manifest', manifestPath])).code).toBe(2);
    expect((await run(base().filter((a) => a !== '--plan-only'))).code).toBe(2);
    expect((await run([...base(), '--execute'])).code).toBe(2);
  });

  it('reads a topology file: a matching production:false entry needs no confirmation', async () => {
    const { rows } = await db.admin.query<{ id: string }>('select system_identifier::text as id from pg_control_system()');
    const topology = join(dir, 'topology.json');
    writeFileSync(topology, JSON.stringify([{ host: db.config.host, port: db.config.port, systemIdentifier: rows[0]?.id, database: db.config.database, production: false }]));
    const { code, out } = await run([...base(), '--topology', topology]);
    expect(code).toBe(0);
    expect(out).toContain('non-production');
    writeFileSync(topology, '{"entries": [{"host": "x"}]}');
    expect((await run([...base(), '--topology', topology])).err).toContain('topology-invalid');
    expect(() => loadTopology(join(dir, 'missing.json'))).toThrow(CloneRefusal);
  });

  it('refuses a manifest file that does not parse', async () => {
    const bad = join(dir, 'bad.json');
    writeFileSync(bad, '{"version": 2}');
    expect((await run(['--from-live', live, '--manifest', bad, '--writers-stopped', '--plan-only'])).err).toContain('manifest-invalid');
  });
});

describe('errors leaving clone name no driver detail', () => {
  it('maps an unexpected driver failure to preflight-failed without its message', async () => {
    const secret = 'hunter2-driver-secret';
    const failure = planClone({
      livePath: live,
      writersStopped: true,
      manifest: manifestOf(MANIFEST as Parameters<typeof manifestOf>[0]),
      target: db.config,
      confirmProduction: `${db.config.host}:${db.config.port}/${db.config.database}`,
      wrapClient: (client) => {
        const original = client.query.bind(client) as (...args: unknown[]) => Promise<unknown>;
        client.query = ((text: unknown, ...rest: unknown[]) => (typeof text === 'string' && text.includes('pg_trigger') ? Promise.reject(new Error(`boom ${secret} ${text}`)) : original(text, ...rest))) as typeof client.query;
        return client;
      },
    });
    const error: unknown = await failure.catch((e: unknown) => e);
    expect(error).toBeInstanceOf(CloneRefusal);
    expect((error as CloneRefusal).refusal).toEqual({ code: 'preflight-failed' });
    expect((error as CloneRefusal).message).toBe('preflight-failed');
    expect(JSON.stringify(error)).not.toContain(secret);
    expect((error as CloneRefusal).cause).toBeUndefined();
  });
});

describe('db-kit clone --dry-run / --execute', () => {
  const modeArgs = (mode: string): string[] => ['--from-live', live, '--manifest', manifestPath, '--writers-stopped', mode, ...confirm()];

  it('--dry-run verifies and rolls back (exit 0), then --execute commits (exit 0) and --json carries the receipt digests', async () => {
    const dry = await run(modeArgs('--dry-run'));
    expect({ code: dry.code, out: dry.out.includes('DRY RUN') }).toEqual({ code: 0, out: true });
    expect(dry.err).toContain('load items: 1 rows');
    expect(((await db.admin.query('select count(*)::int as n from items')).rows[0] as { n: number }).n).toBe(0);
    const done = await run([...modeArgs('--execute'), '--json']);
    expect(done.code).toBe(0);
    const result = JSON.parse(done.out) as { outcome: string; tables: { table: string; rows: number; sha256: string }[] };
    expect(result.outcome).toBe('committed');
    expect(result.tables[0]).toMatchObject({ table: 'items', rows: 1 });
    expect(((await db.admin.query('select count(*)::int as n from items')).rows[0] as { n: number }).n).toBe(1);
    const again = await run(modeArgs('--execute'));
    expect({ code: again.code, err: again.err.trim() }).toEqual({ code: 1, err: 'REFUSED: target-not-empty items' });
  });

  it('exit codes: 4 when COMMIT is aborted, 5 when its outcome is unknown', async () => {
    for (const [mode, code, word] of [
      ['drop-commit', 4, 'ABORTED'],
      ['hold', 5, 'UNKNOWN'],
    ] as const) {
      const fresh = await targetDatabase(server, ['create table items(id bigint generated by default as identity primary key, name text not null)']);
      const proxy = await startCommitProxy({ host: fresh.config.host, port: fresh.config.port }, mode);
      try {
        const target = `postgres://${fresh.config.user}:${fresh.config.password}@127.0.0.1:${proxy.port}/${fresh.config.database}`;
        const result = await run([...modeArgs('--execute').slice(0, -2), '--confirm-production', `127.0.0.1:${proxy.port}/${fresh.config.database}`, '--commit-poll-seconds', '1'], { [TARGET_URL_ENV]: target });
        expect({ code: result.code, named: result.err.includes(word) }).toEqual({ code, named: true });
      } finally {
        await proxy.close();
        await fresh.close();
      }
    }
  }, 60_000);
});
