import { rmSync } from 'node:fs';
import { chmodSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { Client, types } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { CodecManifestInput, TableInput } from '../codecs/manifest.js';
import { startCommitProxy, type CommitMode } from '../test-support/commit-proxy.js';
import { liveSqlite, manifestOf, scratchDir, targetDatabase, type TargetDatabase } from '../test-support/clone-fixture.js';
import { startThrowawayPostgres, type ThrowawayPostgres } from '../test-support/embedded-pg.js';
import { CloneOutcomeError, CloneRefusal, type Refusal } from './errors.js';
import { assertForeignKeysRestored, executeClone, type ExecuteOptions } from './execute.js';
import { readForeignKeys, readIdentity } from './catalog.js';
import { copyField } from './load.js';
import { BIG_DDL, BIG_LIVE, BIG_MANIFEST, NASTY } from '../test-support/big-fixture.js';
import { encodeRow, verifyTable } from './verify.js';
import { loadTable } from './load.js';
import { openSnapshot } from './source.js';
import { postgresOrderBy, sqliteOrderBy } from './order.js';
import { buildCodecs } from '../codecs/bound.js';

let server: ThrowawayPostgres;
const dir = scratchDir();
const open: TargetDatabase[] = [];

beforeAll(async () => {
  server = await startThrowawayPostgres();
}, 180_000);
afterAll(async () => {
  await Promise.allSettled(open.map((db) => db.close()));
  await server?.stop();
  rmSync(dir, { recursive: true, force: true });
}, 60_000);

type Columns = TableInput['columns'];
const int = { codec: 'integer', nullable: false } as const;
const nullableInt = { codec: 'integer', nullable: true } as const;
const text = { codec: 'text', nullable: false } as const;
const table = (columns: Columns, primaryKey: string[] = ['id']): TableInput => ({ columns, primaryKey });

// A small fixture for the adversarial runs: an FK pair and an identity sequence.
const SMALL_MANIFEST = manifestOf({
  version: 1,
  tables: { parent: table({ id: int }), child: table({ id: int, parent_id: int }), items: table({ id: int, name: text }) },
});
const SMALL_DDL = [
  'create table parent(id bigint primary key)',
  'create table child(id bigint primary key, parent_id bigint not null)',
  'alter table child add constraint child_parent_fk foreign key (parent_id) references parent(id)',
  'create table items(id bigint generated by default as identity primary key, name text not null)',
];
const SMALL_LIVE = (): string =>
  liveSqlite(dir, [
    'create table parent(id integer primary key)',
    'create table child(id integer primary key, parent_id integer not null references parent(id))',
    'create table items(id integer primary key, name text not null)',
    'insert into parent values (1), (2)',
    'insert into child values (7, 1), (8, 2)',
    "insert into items values (4, 'x'), (9, 'y')",
  ]);

const confirmationOf = (config: TargetDatabase['config']): string => `${config.host}:${config.port}/${config.database}`;

async function create(ddl: readonly string[], locale?: string): Promise<TargetDatabase> {
  const db = await targetDatabase(server, ddl, locale);
  open.push(db);
  return db;
}

function options(db: TargetDatabase, live: string, manifest: typeof SMALL_MANIFEST, extra: Partial<ExecuteOptions> = {}): ExecuteOptions {
  const target = extra.target ?? db.config;
  return { livePath: live, writersStopped: true, manifest, target, confirmProduction: confirmationOf(target), ...extra };
}

async function refusalOf(run: () => Promise<unknown>): Promise<Refusal> {
  try {
    await run();
  } catch (error) {
    if (error instanceof CloneRefusal) return error.refusal;
    throw error;
  }
  throw new Error('expected a CloneRefusal');
}

/** Everything a rollback must leave exactly as it was: row counts, constraints, sequence state, the receipt schema. */
async function stateOf(db: TargetDatabase, tables: string[], sequences: string[]): Promise<unknown> {
  const counts: Record<string, number> = {};
  for (const name of tables) counts[name] = ((await db.admin.query<{ n: number }>(`select count(*)::int as n from public.${name}`)).rows[0] as { n: number }).n;
  const constraints = (await db.admin.query<{ c: string }>(`select conname || ' ' || pg_get_constraintdef(oid) || ' ' || convalidated::text as c from pg_constraint where connamespace = 'public'::regnamespace order by 1`)).rows.map((r) => r.c);
  const seqs: Record<string, unknown> = {};
  for (const name of sequences) seqs[name] = (await db.admin.query(`select last_value::text, is_called from public.${name}`)).rows[0];
  const receipt = (await db.admin.query("select count(*)::int as n from pg_namespace where nspname = 'db_kit'")).rows[0];
  return { counts, constraints, seqs, receipt };
}

describe('executeClone: a round trip over sides that deliberately differ', () => {
  it('copies every table, verifies it, restarts the sequences and writes the receipt', async () => {
    const db = await create(BIG_DDL);
    const result = await executeClone(options(db, BIG_LIVE(dir), BIG_MANIFEST));
    expect(result.outcome).toBe('committed');
    expect(result.commit?.acknowledged).toBe(true);
    expect(Object.fromEntries(result.tables.map((t) => [t.table, t.rows]))).toEqual({ a: 2, b: 2, node: 3, events: 3, ticket: 3, people: 10, tokens: 3, labels: 4 });
    expect(result.tables.every((t) => /^[0-9a-f]{64}$/.test(t.sha256))).toBe(true);

    // independent reads of what actually landed
    const q = async <R extends object>(sql: string): Promise<R[]> => (await db.admin.query<R & Record<string, unknown>>(sql)).rows;
    const events = await q<{ id: string; label: string; at_ms: string; iso: string; flag: boolean; big: string; dbig: string; doc: unknown; raw: string; note: string | null }>(
      `select id::text, label, to_char(at_ms at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') as at_ms, iso, flag, big::text, dbig::text, doc, encode(raw, 'hex') as raw, note from events order by id`,
    );
    expect(events.map((e) => e.id)).toEqual(['1', '2', '3']);
    expect(events[1]?.label).toBe(NASTY);
    expect(events[0]).toMatchObject({ at_ms: '2024-03-01T08:00:00.124Z', iso: '2026-01-01T00:00:00Z', flag: true, big: '9007199254740993', dbig: '18014398509481986', raw: '00ff5c09', note: null });
    expect(events[1]?.note).toBe('');
    expect(events.map((e) => e.flag)).toEqual([true, false, true]);
    expect(events[0]?.doc).toEqual({ a: [1.0], b: 1 });
    expect(await q('select country, name, age::text from people order by country collate "C", name collate "C"')).toHaveLength(10);
    expect(await q<{ id: string }>('select id::text from tokens order by id')).toEqual([{ id: '00000000-0000-4000-8000-000000000003' }, { id: 'aaaaaaaa-0000-4000-8000-000000000002' }, { id: 'ffffffff-0000-4000-8000-000000000001' }]);
    expect(await q<{ pk: string }>("select b_id::text as pk from a where id = 1")).toEqual([{ pk: '10' }]);

    // sequences: AUTOINCREMENT high-water 5 -> next 6; descending lowest -5 -> next -6
    expect((await q<{ n: string }>("select nextval('events_id_seq')::text as n"))[0]?.n).toBe('6');
    expect((await q<{ n: string }>("select nextval('ticket_id_seq')::text as n"))[0]?.n).toBe('-6');

    // the foreign keys are back, validated, with their original shape
    const fks = await q<{ conname: string; def: string; convalidated: boolean }>("select conname, pg_get_constraintdef(oid) as def, convalidated from pg_constraint where contype = 'f' order by conname");
    expect(fks.map((f) => f.conname)).toEqual(['a_b_fk', 'b_a_fk', 'node_parent_id_fkey']);
    expect(fks.every((f) => f.convalidated)).toBe(true);
    expect(fks[0]?.def).toContain('ON DELETE CASCADE');
    expect(fks[1]?.def).toContain('DEFERRABLE INITIALLY DEFERRED');

    const [receipt] = await q<{ run_id: string; per_table: Record<string, { rows: number; sha256: string }> }>('select run_id::text, per_table from db_kit.clone_receipt');
    expect(receipt?.run_id).toBe(result.runId);
    expect(receipt?.per_table.events).toEqual({ rows: 3, sha256: result.tables.find((t) => t.table === 'events')?.sha256 });
  }, 60_000);

  it('truncates a non-empty target when asked, and refuses it when not', async () => {
    const db = await create(SMALL_DDL);
    await db.admin.query("insert into parent values (99); insert into items(name) values ('old')");
    expect(await refusalOf(() => executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST)))).toEqual({ code: 'target-not-empty', table: 'items' });
    expect(((await db.admin.query('select count(*)::int as n from parent')).rows[0] as { n: number }).n).toBe(1);
    const result = await executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { truncate: true }));
    expect(result.outcome).toBe('committed');
    expect((await db.admin.query('select id::int from parent order by id')).rows).toEqual([{ id: 1 }, { id: 2 }]);
  });
});

describe('executeClone: review follow-ups (session pins, options, SQLite-side keys)', () => {
  it('database defaults of bytea_output=escape and extra_float_digits=0 cannot make verification fail or lie', async () => {
    const manifest = manifestOf({ version: 1, tables: { m: table({ id: int, raw: { codec: 'blob', nullable: false }, r: { codec: 'real', nullable: false } }) } });
    const db = await create(['create table m(id bigint primary key, raw bytea not null, r double precision not null)', "alter database {db} set bytea_output = 'escape'", 'alter database {db} set extra_float_digits = 0']);
    const live = liveSqlite(dir, ['create table m(id integer primary key, raw blob not null, r real not null)', "insert into m values (1, x'68656c6c6f', 0.30000000000000004), (2, x'00ff5c', 1.2345678901234567)"]);
    expect((await executeClone(options(db, live, manifest))).outcome).toBe('committed');
    expect((await db.admin.query("select encode(raw, 'hex') as h, r::text from m order by id")).rows).toEqual([
      { h: '68656c6c6f', r: '0.30000000000000004' },
      { h: '00ff5c', r: '1.2345678901234567' },
    ]);
  });

  it('refuses non-positive or non-integer numeric options instead of "verifying" nothing', async () => {
    const db = await create(SMALL_DDL);
    const live = SMALL_LIVE();
    const bad: [string, number | bigint][] = [['fetchRows', 0], ['fetchRows', -1], ['fetchRows', 2.5], ['batchBytes', 0], ['batchBytes', Number.NaN], ['lockTimeoutMs', 0], ['lockTimeoutMs', -3], ['commitPollMs', -1], ['commitPollMs', Number.NaN], ['maxSlotRetentionBytes', -1n]];
    for (const [name, value] of bad) {
      expect(await refusalOf(() => executeClone(options(db, live, SMALL_MANIFEST, { [name]: value } as Partial<ExecuteOptions>))), `${name}=${String(value)}`).toEqual({ code: 'invalid-option', object: name });
    }
    expect(((await db.admin.query('select count(*)::int as n from parent')).rows[0] as { n: number }).n).toBe(0);
  });

  it('a SQLite foreign key to or from a copy:false table is refused even when Postgres has no such key', async () => {
    const manifest = manifestOf({ version: 1, tables: { items: table({ id: int, name: text, l: nullableInt }), ledger: { copy: false, reason: 'ledger' } } });
    const db = await create(['create table items(id bigint primary key, name text not null, l bigint)', 'create table ledger(id bigint primary key)']);
    const toLedger = liveSqlite(dir, ['create table ledger(id integer primary key)', 'create table items(id integer primary key, name text not null, l integer references ledger(id))']);
    expect(await refusalOf(() => executeClone(options(db, toLedger, manifest)))).toMatchObject({ code: 'foreign-key-to-skipped-table', table: 'items' });
    const fromLedger = liveSqlite(dir, ['create table items(id integer primary key, name text not null, l integer)', 'create table ledger(id integer primary key, item integer references items(id))']);
    expect(await refusalOf(() => executeClone(options(db, fromLedger, manifest)))).toMatchObject({ code: 'foreign-key-to-skipped-table', table: 'items' });
  });
});

describe('executeClone: a column that mixes epoch integers and SQLite datetime() text', () => {
  const manifest = manifestOf({ version: 1, tables: { bindings: table({ id: int, created_at: { codec: 'timestamp-epoch-ms', preserveInteger: false, acceptSqliteDatetimeText: true, nullable: false } }) } });
  const ddl = ['create table bindings(id bigint primary key, created_at timestamptz not null)'];
  const mixed = (): string =>
    liveSqlite(dir, ['create table bindings(id integer primary key, created_at)', "insert into bindings values (1, 1709280000123), (2, '2024-03-01 08:00:00'), (3, '2024-03-01 08:00:00.123'), (4, 1709280000000)"]);

  it('forward: mixed SQLite -> timestamptz, verification passes, a text and an integer for one instant land identical', async () => {
    const db = await create(ddl);
    const result = await executeClone(options(db, mixed(), manifest));
    expect(result.outcome).toBe('committed');
    const rows = (await db.admin.query<{ id: string; at: string }>("select id::text, to_char(created_at at time zone 'UTC', 'YYYY-MM-DD HH24:MI:SS.MS') as at from bindings order by id")).rows;
    expect(rows).toEqual([
      { id: '1', at: '2024-03-01 08:00:00.123' },
      { id: '2', at: '2024-03-01 08:00:00.000' },
      { id: '3', at: '2024-03-01 08:00:00.123' },
      { id: '4', at: '2024-03-01 08:00:00.000' },
    ]);
  });

  it('without the option the same rows are refused by table.column, and nothing is written', async () => {
    const db = await create(ddl);
    const strict = manifestOf({ version: 1, tables: { bindings: table({ id: int, created_at: { codec: 'timestamp-epoch-ms', preserveInteger: false, nullable: false } }) } });
    expect(await refusalOf(() => executeClone(options(db, mixed(), strict)))).toEqual({ code: 'codec-invalid', table: 'bindings', column: 'created_at' });
    expect(((await db.admin.query('select count(*)::int as n from bindings')).rows[0] as { n: number }).n).toBe(0);
  });

  it('a text that is not datetime() output is refused by name, naming nothing else', async () => {
    const db = await create(ddl);
    const live = liveSqlite(dir, ['create table bindings(id integer primary key, created_at)', "insert into bindings values (1, '2024-03-01T08:00:00Z')"]);
    expect(await refusalOf(() => executeClone(options(db, live, manifest)))).toEqual({ code: 'codec-invalid', table: 'bindings', column: 'created_at' });
  });
});

describe('executeClone: copy:false tables', () => {
  it('never copies, verifies, counts or truncates a skipped ledger: its rows on both sides stay exactly where they are', async () => {
    const manifest = manifestOf({ version: 1, tables: { items: table({ id: int, name: text }), _ledger: { copy: false, reason: 'migration ledger' } } });
    const db = await create(['create table items(id bigint primary key, name text not null)', 'create table _ledger(id bigint primary key, note text)', "insert into _ledger values (1, 'applied-in-pg')", "insert into items values (50, 'old')"]);
    const live = liveSqlite(dir, ['create table items(id integer primary key, name text not null)', 'create table _ledger(id integer primary key, note text)', "insert into _ledger values (9, 'sqlite-only')", "insert into items values (4, 'x')"]);
    const result = await executeClone(options(db, live, manifest, { truncate: true }));
    expect(result.outcome).toBe('committed');
    expect(result.tables.map((t) => t.table)).toEqual(['items']);
    expect(result.plan.skippedTables).toEqual([{ table: '_ledger', reason: 'migration ledger' }]);
    expect((await db.admin.query('select id::int, note from _ledger')).rows).toEqual([{ id: 1, note: 'applied-in-pg' }]);
    expect((await db.admin.query('select id::int from items')).rows).toEqual([{ id: 4 }]);
  });
});

describe('executeClone: the target is logically unchanged on every failure', () => {
  const TABLES = ['parent', 'child', 'items'];
  const SEQS = ['items_id_seq'];

  it('a checksum mismatch injected between load and verify rolls back, naming table and column', async () => {
    const db = await create(SMALL_DDL);
    const before = await stateOf(db, TABLES, SEQS);
    const refusal = await refusalOf(() =>
      executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { hooks: { beforeVerify: async (client: Client) => void (await client.query("update public.items set name = 'tampered' where id = 4")) } })),
    );
    expect(refusal).toEqual({ code: 'verification-mismatch', table: 'items', column: 'name' });
    expect(await stateOf(db, TABLES, SEQS)).toEqual(before);
  });

  it('a missing or an extra row on the target is a mismatch too', async () => {
    const db = await create(SMALL_DDL);
    const before = await stateOf(db, TABLES, SEQS);
    const missing = await refusalOf(() => executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { hooks: { beforeVerify: async (c: Client) => void (await c.query('delete from public.items where id = 9')) } })));
    expect(missing).toEqual({ code: 'verification-mismatch', table: 'items' });
    const extra = await refusalOf(() => executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { hooks: { beforeVerify: async (c: Client) => void (await c.query("insert into public.items values (100, 'zz')")) } })));
    expect(extra).toEqual({ code: 'verification-mismatch', table: 'items' });
    expect(await stateOf(db, TABLES, SEQS)).toEqual(before);
  });

  it('a late failure after the foreign keys were dropped puts them back and leaves the data unchanged', async () => {
    const db = await create(SMALL_DDL);
    const before = await stateOf(db, TABLES, SEQS);
    const seen: string[] = [];
    const refusal = await refusalOf(() =>
      executeClone(
        options(db, SMALL_LIVE(), SMALL_MANIFEST, {
          hooks: {
            afterLoad: async (client: Client) => {
              seen.push(JSON.stringify((await client.query("select count(*)::int as n from pg_constraint where contype = 'f' and connamespace = 'public'::regnamespace")).rows));
              throw new Error('boom with a secret value 12345');
            },
          },
        }),
      ),
    );
    expect(refusal).toEqual({ code: 'execute-failed' });
    expect(seen).toEqual(['[{"n":0}]']); // the keys really were gone at that moment
    expect(await stateOf(db, TABLES, SEQS)).toEqual(before);
    expect(JSON.stringify(before)).toContain('child_parent_fk');
  });

  it('a data error in the load (the target rejects a row) is a load-failed refusal naming the table', async () => {
    const db = await create(['create table parent(id bigint primary key)', 'create table child(id bigint primary key, parent_id bigint not null check (parent_id < 2))', ...SMALL_DDL.slice(2)]);
    const refusal = await refusalOf(() => executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST)));
    expect(refusal).toEqual({ code: 'load-failed', table: 'child' });
  });

  it('a foreign key violated by the data fails when it is re-added, and the target is unchanged', async () => {
    const db = await create(SMALL_DDL);
    const live = liveSqlite(dir, [
      'create table parent(id integer primary key)',
      'create table child(id integer primary key, parent_id integer not null)',
      'create table items(id integer primary key, name text not null)',
      'insert into child values (7, 55)',
    ]);
    const before = await stateOf(db, TABLES, SEQS);
    expect(await refusalOf(() => executeClone(options(db, live, SMALL_MANIFEST)))).toEqual({ code: 'execute-failed' });
    expect(await stateOf(db, TABLES, SEQS)).toEqual(before);
  });

  it('a held table lock is a lock-timeout refusal, not a hang', async () => {
    const db = await create(SMALL_DDL);
    const holder = await db.admin.query('begin').then(() => db.admin.query('lock table items in access exclusive mode'));
    expect(holder).toBeDefined();
    try {
      const started = performance.now();
      expect(await refusalOf(() => executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { lockTimeoutMs: 300 })))).toEqual({ code: 'lock-timeout' });
      expect(performance.now() - started).toBeLessThan(5000);
    } finally {
      await db.admin.query('rollback');
    }
  });

  it('--dry-run does everything and rolls back: data, sequences, constraints and schema are untouched', async () => {
    const db = await create(SMALL_DDL);
    const before = await stateOf(db, TABLES, SEQS);
    const result = await executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { dryRun: true }));
    expect(result.outcome).toBe('dry-run');
    expect(result.tables.map((t) => t.rows)).toEqual([2, 2, 2]);
    expect(result.commit).toBeNull();
    expect(await stateOf(db, TABLES, SEQS)).toEqual(before);
    // and a real run after it still works
    expect((await executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST))).outcome).toBe('committed');
  });

  it('refuses codec-invalid source data naming table.column, and leaves the target unchanged', async () => {
    const db = await create(SMALL_DDL);
    const live = liveSqlite(dir, [
      'create table parent(id integer primary key)',
      'create table child(id integer primary key, parent_id integer not null)',
      'create table items(id integer primary key, name)',
      'insert into items values (1, 5)', // an INTEGER where the manifest says text
    ]);
    const before = await stateOf(db, TABLES, SEQS);
    expect(await refusalOf(() => executeClone(options(db, live, SMALL_MANIFEST)))).toEqual({ code: 'codec-invalid', table: 'items', column: 'name' });
    expect(await stateOf(db, TABLES, SEQS)).toEqual(before);
  });
});

describe('executeClone: COMMIT outcome through a misbehaving connection', () => {
  async function run(mode: CommitMode, extra: { holdMs?: number; commitPollMs: number }) {
    const db = await create(SMALL_DDL);
    const proxy = await startCommitProxy({ host: db.config.host, port: db.config.port }, mode, extra.holdMs === undefined ? {} : { holdMs: extra.holdMs });
    const target = { ...db.config, port: proxy.port };
    return { db, proxy, attempt: executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { target, commitPollMs: extra.commitPollMs })) };
  }
  const rowsOf = async (db: TargetDatabase): Promise<number> => ((await db.admin.query('select count(*)::int as n from parent')).rows[0] as { n: number }).n;

  it('(a) COMMIT forwarded, reply dropped: reported committed, unacknowledged, and really committed', async () => {
    const { db, proxy, attempt } = await run('drop-reply', { commitPollMs: 10_000 });
    try {
      const result = await attempt;
      expect(result.outcome).toBe('committed');
      expect(result.commit?.acknowledged).toBe(false);
      expect(await rowsOf(db)).toBe(2);
      expect(((await db.admin.query<{ id: string }>('select run_id::text as id from db_kit.clone_receipt')).rows[0] as { id: string }).id).toBe(result.runId);
    } finally {
      await proxy.close();
    }
  }, 60_000);

  it('(b) COMMIT dropped: reported aborted, and nothing is on the target', async () => {
    const { db, proxy, attempt } = await run('drop-commit', { commitPollMs: 10_000 });
    try {
      const error: unknown = await attempt.catch((e: unknown) => e);
      expect(error).toBeInstanceOf(CloneOutcomeError);
      expect((error as CloneOutcomeError).outcome).toBe('aborted');
      expect(await rowsOf(db)).toBe(0);
      expect(((await db.admin.query("select count(*)::int as n from pg_namespace where nspname = 'db_kit'")).rows[0] as { n: number }).n).toBe(0);
    } finally {
      await proxy.close();
    }
  }, 60_000);

  it('(c) COMMIT held while the transaction is in progress: waits, then reports what actually happened', async () => {
    const { db, proxy, attempt } = await run('hold', { holdMs: 1500, commitPollMs: 20_000 });
    try {
      await proxy.intercepted;
      const xid = ((await db.admin.query<{ x: string }>("select backend_xid::text as x from pg_stat_activity where application_name = 'db-kit-clone' and backend_xid is not null")).rows[0] as { x: string }).x;
      expect(((await db.admin.query<{ s: string }>('select txid_status($1::bigint) as s', [xid])).rows[0] as { s: string }).s).toBe('in progress');
      const result = await attempt;
      expect(result.commit?.acknowledged).toBe(false);
      expect(await rowsOf(db)).toBe(2);
    } finally {
      await proxy.close();
    }
  }, 60_000);

  it('(c2) COMMIT held past the bounded wait: UNKNOWN, never retried', async () => {
    const { db, proxy, attempt } = await run('hold', { commitPollMs: 1000 });
    try {
      const error: unknown = await attempt.catch((e: unknown) => e);
      expect(error).toBeInstanceOf(CloneOutcomeError);
      expect((error as CloneOutcomeError).outcome).toBe('unknown');
      await proxy.close(); // the held session goes away: the server rolls the transaction back
      await db.admin.query('select pg_sleep(0.3)');
      expect(await rowsOf(db)).toBe(0);
    } finally {
      await proxy.close();
    }
  }, 60_000);
});

describe('executeClone: locks and identity', () => {
  it('holds ACCESS EXCLUSIVE locks on the copied tables for the whole transaction', async () => {
    const db = await create(SMALL_DDL);
    const attempts: string[] = [];
    const result = await executeClone(
      options(db, SMALL_LIVE(), SMALL_MANIFEST, {
        hooks: {
          afterLoad: async () => {
            const rival = new Client({ host: db.config.host, port: db.config.port, user: db.config.user, password: db.config.password, database: db.config.database });
            await rival.connect();
            try {
              await rival.query("set lock_timeout = '300ms'");
              await rival.query("insert into public.items(name) values ('sneak')");
              attempts.push('inserted');
            } catch (error) {
              attempts.push((error as { code?: string }).code ?? 'other');
            } finally {
              await rival.end();
            }
          },
        },
      }),
    );
    expect(attempts).toEqual(['55P03']);
    expect(result.outcome).toBe('committed');
    expect(((await db.admin.query('select count(*)::int as n from items')).rows[0] as { n: number }).n).toBe(2);
  });

  it('a COMMIT the server itself rejects (a deferred constraint) is ABORTED at once, without waiting on txid_status', async () => {
    const db = await create(SMALL_DDL);
    const error: unknown = await executeClone(
      options(db, SMALL_LIVE(), SMALL_MANIFEST, {
        commitPollMs: 0,
        hooks: {
          beforeCommit: async (client: Client) => {
            await client.query('alter table public.child alter constraint child_parent_fk deferrable initially deferred');
            await client.query('insert into public.child values (999, 123456)');
          },
        },
      }),
    ).catch((e: unknown) => e);
    expect(error).toBeInstanceOf(CloneOutcomeError);
    expect((error as CloneOutcomeError).outcome).toBe('aborted');
    expect(((await db.admin.query('select count(*)::int as n from parent')).rows[0] as { n: number }).n).toBe(0);
  });

  it('orders text keys bytewise even when the database collation is not C', async (ctx) => {
    // ICU where the server has it, a libc locale otherwise; both order 'apple' before 'Banana', unlike C.
    const locales = ["locale_provider icu icu_locale 'en-US'", "lc_collate 'en_US.UTF-8' lc_ctype 'en_US.UTF-8'", "lc_collate 'en_US.utf8' lc_ctype 'en_US.utf8'"];
    let db: TargetDatabase | undefined;
    for (const locale of locales) {
      try {
        db = await create(['create table words(w text primary key)'], locale);
        break;
      } catch {
        // try the next one
      }
    }
    if (!db) return ctx.skip(); // no non-C collation on this server: the case is unobservable here
    const order = (await db.admin.query<{ w: string }>("select w from (values ('Banana'), ('apple')) v(w) order by w")).rows.map((r) => r.w);
    expect(order).toEqual(['apple', 'Banana']); // the database really is not C
    const manifest = manifestOf({ version: 1, tables: { words: table({ w: text }, ['w']) } });
    const live = liveSqlite(dir, ['create table words(w text primary key)', "insert into words values ('apple'), ('Apple2'), ('Banana'), ('cherry'), ('Zebra'), ('zebra')"]);
    expect((await executeClone(options(db, live, manifest))).outcome).toBe('committed');
  });

  it('locks tables joined to a copied table by a foreign key, not only the copied ones', async () => {
    const db = await create([...SMALL_DDL, 'create schema other', 'create table other.ref(parent_id bigint references public.parent(id))']);
    await db.admin.query('begin');
    await db.admin.query('lock table other.ref in access exclusive mode');
    try {
      expect(await refusalOf(() => executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { lockTimeoutMs: 300 })))).toEqual({ code: 'lock-timeout' });
    } finally {
      await db.admin.query('rollback');
    }
  });

  it('after a lost COMMIT reply, a reconnect that lands on a different server is UNKNOWN, not COMMITTED', async () => {
    const other = await startThrowawayPostgres();
    try {
      const db = await create(SMALL_DDL);
      // a decoy server holding a database of the very same name, so a reconnect there succeeds and only the system identifier differs
      const rootOther = new Client({ ...other.config, ssl: false });
      await rootOther.connect();
      await rootOther.query(`create database ${db.config.database}`);
      await rootOther.end();
      const decoy = await targetDatabase(other, []);
      // make the decoy answer 'committed' for any transaction id the real server could hand out, so only the identity check can stop a wrong claim
      const ahead = Number(((await db.admin.query<{ x: string }>('select txid_current()::text as x')).rows[0] as { x: string }).x) + 200;
      while (Number(((await decoy.admin.query<{ x: string }>('select txid_current()::text as x')).rows[0] as { x: string }).x) < ahead);
      const proxy = await startCommitProxy({ host: db.config.host, port: db.config.port }, 'drop-reply', { redirectAfter: { host: other.config.host, port: other.config.port } });
      try {
        const target = { ...db.config, port: proxy.port };
        const error: unknown = await executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { target, commitPollMs: 3000 })).catch((e: unknown) => e);
        expect(error).toBeInstanceOf(CloneOutcomeError);
        expect((error as CloneOutcomeError).outcome).toBe('unknown');
        // the commit did in fact happen on the real server: the identity check is what stopped us claiming it from the wrong one
        expect(((await db.admin.query('select count(*)::int as n from parent')).rows[0] as { n: number }).n).toBe(2);
      } finally {
        await proxy.close();
        await decoy.close();
      }
    } finally {
      await other.stop();
    }
  }, 90_000);
});

describe('assertForeignKeysRestored', () => {
  it('compares every catalog field of every captured key and the size of the set', async () => {
    const db = await create(SMALL_DDL);
    const oids = (await db.admin.query<{ oid: number }>("select oid::int as oid from pg_class where relname in ('parent', 'child') and relnamespace = 'public'::regnamespace")).rows.map((r) => r.oid);
    await db.admin.query("select set_config('search_path', '', false)");
    const identity = await readIdentity(db.admin);
    const captured = await readForeignKeys(db.admin, oids, identity.serverVersionNum);
    expect(captured).toHaveLength(1);
    const [fk] = captured;
    if (!fk) throw new Error('fixture has no foreign key');
    await assertForeignKeysRestored(db.admin, oids, identity, captured);
    const tampered: Partial<typeof fk>[] = [{ confdeltype: 'c' }, { confupdtype: 'c' }, { confmatchtype: 'f' }, { deferrable: true }, { deferred: true }, { validated: false }, { conkey: '{9}' }, { confkey: '{9}' }, { conpfeqop: '{1}' }, { indexName: 'other' }, { definition: 'x' }, { refOid: 1 }, { tableOid: 1 }, { enforced: false }];
    for (const change of tampered) {
      expect(await refusalOf(() => assertForeignKeysRestored(db.admin, oids, identity, [{ ...fk, ...change }])), JSON.stringify(change)).toEqual({ code: 'foreign-keys-changed', table: 'child', object: 'child_parent_fk' });
    }
    expect(await refusalOf(() => assertForeignKeysRestored(db.admin, oids, identity, [fk, { ...fk, name: 'phantom' }]))).toEqual({ code: 'foreign-keys-changed' });
    expect(await refusalOf(() => assertForeignKeysRestored(db.admin, oids, identity, []))).toEqual({ code: 'foreign-keys-changed' });
  });
});

describe('executeClone: review follow-ups', () => {
  const rowsOf = async (db: TargetDatabase): Promise<number> => ((await db.admin.query('select count(*)::int as n from parent')).rows[0] as { n: number }).n;

  it('a SQLSTATE-bearing COMMIT error is not proof of abort: the transaction status decides (a pooler timed out after the server committed)', async () => {
    const db = await create(SMALL_DDL);
    const proxy = await startCommitProxy({ host: db.config.host, port: db.config.port }, 'error-frame');
    try {
      const result = await executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { target: { ...db.config, port: proxy.port }, commitPollMs: 5000 }));
      expect(result.outcome).toBe('committed');
      expect(result.commit?.acknowledged).toBe(false);
      expect(await rowsOf(db)).toBe(2);
    } finally {
      await proxy.close();
    }
  }, 60_000);

  /** Make the snapshot directory undeletable once the transaction is over, and hand the test its path to repair. */
  const undeletable = (paths: string[]) => (directory: string) => {
    paths.push(directory);
    chmodSync(directory, 0o500);
  };
  const repair = (paths: string[]): void => {
    for (const directory of paths) {
      if (existsSync(directory)) {
        chmodSync(directory, 0o700);
        rmSync(directory, { recursive: true, force: true });
      }
    }
  };

  it('a cleanup failure after COMMIT does not replace the committed result', async () => {
    const db = await create(SMALL_DDL);
    const paths: string[] = [];
    try {
      const result = await executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { hooks: { afterOutcome: undeletable(paths) } }));
      expect(result.outcome).toBe('committed');
      expect(result.cleanupWarning).toBe('snapshot-cleanup-failed');
      expect(await rowsOf(db)).toBe(2);
    } finally {
      repair(paths);
    }
  });

  it('a cleanup failure does not replace an UNKNOWN commit outcome either', async () => {
    const db = await create(SMALL_DDL);
    const proxy = await startCommitProxy({ host: db.config.host, port: db.config.port }, 'hold');
    const paths: string[] = [];
    try {
      const error: unknown = await executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { target: { ...db.config, port: proxy.port }, commitPollMs: 800, hooks: { afterOutcome: undeletable(paths) } })).catch((e: unknown) => e);
      expect(error).toBeInstanceOf(CloneOutcomeError);
      expect((error as CloneOutcomeError).outcome).toBe('unknown');
      expect((error as CloneOutcomeError).cleanupFailed).toBe(true);
    } finally {
      await proxy.close();
      repair(paths);
    }
  }, 60_000);

  const RECEIPT_DDL = ['create schema db_kit', 'create table db_kit.clone_receipt(run_id uuid primary key, started_at timestamptz not null, manifest_sha text not null, per_table jsonb not null)'];

  it('locks an existing receipt table with the copied tables: a trigger cannot be added to it mid-run', async () => {
    const db = await create([...SMALL_DDL, ...RECEIPT_DDL, 'create function db_kit.noop() returns trigger language plpgsql as $$ begin return new; end $$']);
    const attempts: string[] = [];
    const result = await executeClone(
      options(db, SMALL_LIVE(), SMALL_MANIFEST, {
        hooks: {
          afterLoad: async () => {
            const rival = new Client({ host: db.config.host, port: db.config.port, user: db.config.user, password: db.config.password, database: db.config.database });
            await rival.connect();
            try {
              await rival.query("set lock_timeout = '300ms'");
              await rival.query('create trigger t before insert on db_kit.clone_receipt for each row execute function db_kit.noop()');
              attempts.push('created');
            } catch (error) {
              attempts.push((error as { code?: string }).code ?? 'other');
            } finally {
              await rival.end();
            }
          },
        },
      }),
    );
    expect(attempts).toEqual(['55P03']);
    expect(result.outcome).toBe('committed');
  });

  it('re-validates the receipt table before inserting: a trigger that slipped in after preflight is refused', async () => {
    const db = await create([...SMALL_DDL, ...RECEIPT_DDL, 'create function db_kit.noop() returns trigger language plpgsql as $$ begin return new; end $$']);
    const refusal = await refusalOf(() =>
      executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { hooks: { afterLoad: async (c: Client) => void (await c.query('create trigger t before insert on db_kit.clone_receipt for each row execute function db_kit.noop()')) } })),
    );
    expect(refusal).toEqual({ code: 'receipt-table-invalid', table: 'db_kit.clone_receipt' });
    expect(await rowsOf(db)).toBe(0);
  });

  it('verification does not use global pg type parsers: a lowercasing TEXT parser cannot hide a real difference', async () => {
    const db = await create(SMALL_DDL);
    types.setTypeParser(25, (value: string) => value.toLowerCase());
    try {
      const refusal = await refusalOf(() =>
        executeClone(options(db, SMALL_LIVE(), SMALL_MANIFEST, { hooks: { beforeVerify: async (c: Client) => void (await c.query("update public.items set name = 'X' where id = 4")) } })),
      );
      expect(refusal).toEqual({ code: 'verification-mismatch', table: 'items', column: 'name' });
    } finally {
      types.setTypeParser(25, (value: string) => value);
    }
  });

  it('loadTable and verifyTable refuse invalid UTF-8 themselves, behind the preflight scan', async () => {
    const db = await create(['create table items(id bigint primary key, name text not null)']);
    const manifest = manifestOf({ version: 1, tables: { items: table({ id: int, name: text }) } });
    const live = liveSqlite(dir, ['create table items(id integer primary key, name text not null)', "insert into items values (1, cast(x'80' as text))"]);
    const sqlite = openSnapshot(live);
    try {
      const spec = manifest.tables.items;
      if (!spec) throw new Error('fixture');
      const codecs = buildCodecs(manifest);
      const columns = ['id', 'name'].map((c) => codecs.column('items', c));
      const refused = { code: 'source-invalid-utf8', table: 'items', column: 'name' };
      expect(await refusalOf(() => loadTable({ client: db.admin, db: sqlite, table: 'items', columns, orderBy: sqliteOrderBy(spec), batchBytes: 1 << 20 }))).toEqual(refused);
      await db.admin.query('truncate items');
      await db.admin.query("insert into items values (1, E'\\357\\277\\275')"); // what a lossy decode would have loaded
      await db.admin.query('begin');
      try {
        expect(await refusalOf(() => verifyTable({ client: db.admin, db: sqlite, table: 'items', columns, primaryKey: ['id'], sqliteOrderBy: sqliteOrderBy(spec), postgresOrderBy: postgresOrderBy(spec), fetchRows: 100 }))).toEqual(refused);
      } finally {
        await db.admin.query('rollback');
      }
    } finally {
      sqlite.close();
    }
  });
});

describe('COPY and verification encodings', () => {
  it('escapes backslash, tab, newline and CR, keeps \\N and \\. literal, and renders bytea, NULL, -0', () => {
    expect(copyField('a\tb\nc\rd\\e')).toBe('a\\tb\\nc\\rd\\\\e');
    expect(copyField('\\N')).toBe('\\\\N');
    expect(copyField('\\.')).toBe('\\\\.');
    expect(copyField(null)).toBe('\\N');
    expect(copyField(Buffer.from([0, 255]))).toBe('\\\\x00ff');
    expect(copyField(true)).toBe('t');
    expect(copyField(2n ** 62n)).toBe('4611686018427387904');
    expect(copyField(-0)).toBe('-0');
  });

  it('the row encoding is length-prefixed: ("ab","c") differs from ("a","bc"), NULL from the empty string', () => {
    const codecs = buildCodecs(manifestOf({ version: 1, tables: { t: table({ id: int, x: { codec: 'text', nullable: true }, y: { codec: 'text', nullable: true } }) } }));
    const columns = ['x', 'y'].map((c) => codecs.column('t', c));
    const e = (x: string | null, y: string | null): string => encodeRow(columns, [x, y], 'sqlite').toString('hex');
    expect(e('ab', 'c')).not.toBe(e('a', 'bc'));
    expect(e(null, 'a')).not.toBe(e('', 'a'));
    expect(e('ab', 'c')).toBe(encodeRow(columns, ['ab', 'c'], 'postgres').toString('hex'));
  });
});
