import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import Database from 'better-sqlite3';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { manifestOf, scratchDir, targetDatabase, type TargetDatabase } from '../test-support/clone-fixture.js';
import { startThrowawayPostgres, type ThrowawayPostgres } from '../test-support/embedded-pg.js';
import { postgresUrl } from '../testing/postgres.js';
import { CloneRefusal } from './errors.js';
import { runExportSqliteCli, scrubMessage } from './export-cli.js';
import { buildExportTemplate, exportToSqlite, reverseManifestFor, type SqliteExportApp } from './export-sqlite.js';

let server: ThrowawayPostgres;
const dir = scratchDir();
const open: TargetDatabase[] = [];
beforeAll(async () => {
  server = await startThrowawayPostgres();
}, 180_000);
afterAll(async () => {
  await Promise.allSettled(open.map((db) => db.close()));
  await server?.stop();
  rmSync(dir, { recursive: true, force: true });
}, 60_000);

const MANIFEST = manifestOf({
  version: 1,
  tables: {
    settings: { primaryKey: ['key'], columns: { key: { codec: 'text', nullable: false }, value: { codec: 'text', nullable: false } } },
    events: { primaryKey: ['id'], columns: { id: { codec: 'integer', nullable: false }, label: { codec: 'text', nullable: false } } },
  },
});
const LEDGER_IDS = ['001-init', '002-events'];
const PG_DDL = [
  'create table migrations_ledger(id text primary key)',
  `insert into migrations_ledger values ${LEDGER_IDS.map((id) => `('${id}')`).join(', ')}`,
  'create table settings(key text primary key, value text not null)',
  "insert into settings values ('seeded', 'from-postgres'), ('theme', 'dark')",
  'create table events(id bigint generated by default as identity primary key, label text not null)',
  "insert into events(label) values ('a'), ('b'), ('c')",
];

let templatesBuilt = 0;
function fakeApp(extra: Partial<SqliteExportApp> = {}): SqliteExportApp {
  return {
    manifest: MANIFEST,
    skipTables: { migrations_ledger: 'the template carries its own ledger' },
    buildTemplate(path) {
      templatesBuilt++;
      const db = new Database(path);
      db.exec('create table migrations_ledger(id text primary key)');
      for (const id of LEDGER_IDS) db.prepare('insert into migrations_ledger values (?)').run(id);
      db.exec('create table settings(key text primary key, value text not null)');
      db.exec("insert into settings values ('seeded', 'from-migration')"); // a migration seeding a copied table
      db.exec('create table events(id integer primary key autoincrement, label text not null)');
      db.close();
    },
    ledger: { query: 'select id from migrations_ledger', expected: () => LEDGER_IDS },
    ...extra,
  };
}

async function create(): Promise<TargetDatabase> {
  const db = await targetDatabase(server, PG_DDL);
  open.push(db);
  return db;
}

const confirmationOf = (db: TargetDatabase): string => `${db.config.host}:${db.config.port}/${db.config.database}`;
let counter = 0;
const outputPath = (): string => {
  const folder = join(dir, `out-${++counter}`);
  mkdirSync(folder);
  return join(folder, 'app.db');
};
const exportDirs = (): string[] => readdirSync(tmpdir()).filter((name) => name.startsWith('db-kit-export-'));

async function run(args: string[], db: TargetDatabase, app: SqliteExportApp = fakeApp(), env: NodeJS.ProcessEnv = { DATABASE_URL: postgresUrl(db.config) }): Promise<{ code: number; out: string; err: string }> {
  let out = '';
  let err = '';
  const code = await runExportSqliteCli(args, { out: (t) => void (out += `${t}\n`), err: (t) => void (err += `${t}\n`) }, env, app);
  return { code, out, err };
}

describe('exportToSqlite', () => {
  it('round trip: every source row arrives, the ledger keeps the template rows, and the seeded row is cleared from the template only', async () => {
    const db = await create();
    const target = outputPath();
    const before = exportDirs();
    const result = await run(['export-sqlite', target, '--writers-stopped', '--confirm-production', confirmationOf(db)], db);
    expect(result.err).toBe('');
    expect(result.code).toBe(0);
    const summary = JSON.parse(result.out) as Record<string, unknown>;
    expect(summary).toMatchObject({ ok: true, command: 'export-sqlite', outcome: 'written', path: target, tables: 2, rows: 5, warnings: [], templateRowsCleared: ['settings'] });
    expect(summary.receiptPath).toBe(`${target}.receipt.json`);
    expect(result.out).not.toContain(db.config.password);
    expect(exportDirs()).toEqual(before);

    const exported = new Database(target, { readonly: true });
    expect(exported.prepare('select key, value from settings order by key').all()).toEqual([
      { key: 'seeded', value: 'from-postgres' },
      { key: 'theme', value: 'dark' },
    ]);
    expect(exported.prepare('select id, label from events order by id').all()).toEqual([
      { id: 1, label: 'a' },
      { id: 2, label: 'b' },
      { id: 3, label: 'c' },
    ]);
    expect(exported.prepare('select id from migrations_ledger order by id').all()).toEqual(LEDGER_IDS.map((id) => ({ id })));
    expect(exported.prepare("select seq from sqlite_sequence where name = 'events'").get()).toEqual({ seq: 3 });
    exported.close();
  }, 120_000);

  it('a dry run verifies and writes nothing', async () => {
    const db = await create();
    const target = outputPath();
    const result = await run(['export-sqlite', target, '--writers-stopped', '--dry-run', '--confirm-production', confirmationOf(db)], db);
    expect(result.code).toBe(0);
    expect(JSON.parse(result.out)).toMatchObject({ outcome: 'dry-run', path: null });
    expect(existsSync(target)).toBe(false);
  }, 120_000);

  it('refuses without --writers-stopped before building anything', async () => {
    const db = await create();
    const target = outputPath();
    const built = templatesBuilt;
    const before = exportDirs();
    const result = await run(['export-sqlite', target, '--confirm-production', confirmationOf(db)], db);
    expect(result.code).toBe(1);
    expect(JSON.parse(result.err)).toMatchObject({ ok: false, command: 'export-sqlite', refusal: { code: 'writers-not-stopped' } });
    expect(templatesBuilt).toBe(built);
    expect(existsSync(target)).toBe(false);
    expect(exportDirs()).toEqual(before);
  });

  it('refuses an existing target and leaves it untouched', async () => {
    const db = await create();
    const target = outputPath();
    writeFileSync(target, 'not a database');
    const before = exportDirs();
    const result = await run(['export-sqlite', target, '--writers-stopped', '--confirm-production', confirmationOf(db)], db);
    expect(result.code).toBe(1);
    expect(JSON.parse(result.err)).toMatchObject({ refusal: { code: 'sqlite-target-exists' } });
    expect(readFileSync(target, 'utf8')).toBe('not a database');
    expect(exportDirs()).toEqual(before);
  }, 120_000);

  it('refuses when the Postgres ledger differs from the code, naming both ids, and leaves no work directory', async () => {
    const db = await create();
    await db.admin.query("insert into migrations_ledger values ('999-from-the-future')");
    await db.admin.query("delete from migrations_ledger where id = '002-events'");
    const target = outputPath();
    const before = exportDirs();
    const result = await run(['export-sqlite', target, '--writers-stopped', '--confirm-production', confirmationOf(db)], db);
    expect(result.code).toBe(1);
    const error = JSON.parse(result.err) as { refusal: unknown; error: string };
    expect(error.refusal).toEqual({ code: 'ledger-mismatch' });
    expect(error.error).toContain('missing from Postgres [002-events]');
    expect(error.error).toContain('unknown to this code [999-from-the-future]');
    expect(existsSync(target)).toBe(false);
    expect(exportDirs()).toEqual(before);
  }, 120_000);

  it('a throwing smoke open is a warning: the file stays in place and the exit code is 3', async () => {
    const db = await create();
    const target = outputPath();
    const result = await run(['export-sqlite', target, '--writers-stopped', '--confirm-production', confirmationOf(db)], db, fakeApp({ smoke: () => { throw new Error('pending migrations: 003'); } }));
    expect(result.code).toBe(3);
    expect(existsSync(target)).toBe(true);
    const { warnings } = JSON.parse(result.out) as { warnings: string[] };
    expect(warnings).toEqual(['smoke-open-failed: pending migrations: 003']);
  }, 120_000);

  it('smoke receives a copy, so the published file is untouched', async () => {
    const db = await create();
    const target = outputPath();
    let seen = '';
    const result = await exportToSqlite({ app: fakeApp({ smoke: (copy) => void (seen = copy) }), source: db.config, toSqlitePath: target, writersStopped: true, confirmProduction: confirmationOf(db) });
    expect(result.warnings).toEqual([]);
    expect(seen).not.toBe('');
    expect(seen).not.toBe(target);
  }, 120_000);

  it('a ledger-query failure is a bare refusal, never a driver message', async () => {
    const db = await create();
    const failure = await exportToSqlite({ app: fakeApp({ ledger: { query: 'select id from no_such_table', expected: () => LEDGER_IDS } }), source: db.config, toSqlitePath: outputPath(), writersStopped: true, confirmProduction: confirmationOf(db) }).catch((error: unknown) => error);
    expect(failure).toBeInstanceOf(CloneRefusal);
    expect((failure as CloneRefusal).refusal).toEqual({ code: 'source-read-failed' });
  }, 120_000);

  it('never prints the URL password, even when an app message quotes the URL', async () => {
    const db = await create();
    const url = `${postgresUrl(db.config)}`;
    const target = outputPath();
    const leaky = fakeApp({ smoke: () => { throw new Error(`could not open ${url} with password ${db.config.password}`); } });
    const result = await run(['export-sqlite', target, '--writers-stopped', '--confirm-production', confirmationOf(db)], db, leaky);
    expect(result.code).toBe(3);
    expect(result.out).toContain('[redacted]');
    expect(result.out).not.toContain(db.config.password);
    expect(result.out).not.toContain(url);
  }, 120_000);
});

describe('scrubMessage', () => {
  it('replaces the URL, the raw and decoded password, and any other URL userinfo', () => {
    const url = 'postgres://app:p%40ss@db.example:5432/app';
    const text = scrubMessage(`failed ${url} (p@ss / p%40ss) and also postgres://other:hunter2@elsewhere/x`, url);
    expect(text).not.toMatch(/p%40ss|p@ss|hunter2|app:/);
    expect(text).toContain('[redacted]');
  });
});

describe('CLI usage and sqlite-template', () => {
  it('exits 2 on a usage error and 1 on a missing, invalid or non-postgres source URL', async () => {
    const db = await create();
    expect((await run(['export-sqlite'], db)).code).toBe(2);
    expect((await run(['nonsense', 'x'], db)).code).toBe(2);
    expect((await run(['export-sqlite', outputPath(), '--bogus'], db)).code).toBe(2);
    const target = outputPath();
    expect(JSON.parse((await run(['export-sqlite', target, '--writers-stopped'], db, fakeApp(), {})).err)).toMatchObject({ refusal: { code: 'source-url-missing' } });
    expect(JSON.parse((await run(['export-sqlite', target, '--writers-stopped'], db, fakeApp(), { DATABASE_URL: 'nonsense' })).err)).toMatchObject({ refusal: { code: 'source-url-invalid' } });
    expect(JSON.parse((await run(['export-sqlite', target, '--writers-stopped'], db, fakeApp(), { DATABASE_URL: 'file:x.db' })).err)).toMatchObject({ refusal: { code: 'source-not-postgres' } });
  });

  it('reads the URL from a custom environment variable', async () => {
    const db = await create();
    let err = '';
    const code = await runExportSqliteCli(['export-sqlite', outputPath(), '--writers-stopped'], { out: () => undefined, err: (t) => void (err += t) }, { DATABASE_URL: postgresUrl(db.config) }, fakeApp(), { sourceUrlEnv: 'APP_PG_URL' });
    expect(code).toBe(1);
    expect(JSON.parse(err)).toMatchObject({ refusal: { code: 'source-url-missing' } });
  });

  it('sqlite-template writes a file empty of copied rows, keeping the ledger, and refuses an existing path', async () => {
    const db = await create();
    const target = join(dir, 'template.db');
    const result = await run(['sqlite-template', target], db);
    expect(result.code).toBe(0);
    expect(JSON.parse(result.out)).toEqual({ ok: true, command: 'sqlite-template', templateRowsCleared: ['settings'] });
    const template = new Database(target, { readonly: true });
    expect(template.prepare('select count(*) as n from settings').get()).toEqual({ n: 0 });
    expect(template.prepare('select count(*) as n from migrations_ledger').get()).toEqual({ n: 2 });
    template.close();
    const again = await run(['sqlite-template', target], db);
    expect(again.code).toBe(1);
    expect(JSON.parse(again.err)).toMatchObject({ refusal: { code: 'sqlite-target-exists' } });
  });
});

describe('reverseManifestFor and buildExportTemplate', () => {
  it('declares the skipped tables and drops a copied table that the app skips', () => {
    const manifest = reverseManifestFor(fakeApp({ skipTables: { migrations_ledger: 'ledger', events: 'not reversible' } }));
    expect(Object.keys(manifest.tables)).toEqual(['settings']);
    expect(manifest.skipped).toEqual({ migrations_ledger: { reason: 'ledger' }, events: { reason: 'not reversible' } });
  });

  it('does not delete rows from a skipped table, and leaves a skipped table that is absent from SQLite alone', async () => {
    const path = join(dir, 'skip-template.db');
    const cleared = await buildExportTemplate(fakeApp({ skipTables: { migrations_ledger: 'ledger', not_in_sqlite: 'derived' } }), path);
    expect(cleared).toEqual(['settings']);
    const db = new Database(path, { readonly: true });
    expect(db.prepare('select count(*) as n from migrations_ledger').get()).toEqual({ n: 2 });
    db.close();
  });
});
